[package]
name = "smooth-river-stones"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = "0.18"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
anyhow = "*"
nom = "7"

serde = "1"
serde_json = "1"
url = "2"

[dependencies.web-sys]
version = "0.3"
features = ["Request"]